import { StyleSheet } from "react-native";
import { adminPalette } from "@shared/constants";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: adminPalette.cream,
    paddingHorizontal: 18,
    paddingTop: 56,
  },
  center: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: adminPalette.cream,
  },
  centerPadded: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: adminPalette.cream,
    padding: 22,
  },
  loginCard: {
    marginTop: 92,
    borderRadius: 18,
    backgroundColor: adminPalette.card,
    padding: 22,
    borderWidth: 1,
    borderColor: "#E9DCCF",
  },
  header: {
    marginBottom: 18,
  },
  script: {
    color: adminPalette.cocoa,
    fontSize: 28,
    marginBottom: 4,
  },
  title: {
    color: adminPalette.coffee,
    fontSize: 34,
    fontWeight: "700",
  },
  sectionTitle: {
    color: adminPalette.coffee,
    fontSize: 20,
    fontWeight: "700",
    marginTop: 18,
    marginBottom: 8,
  },
  card: {
    backgroundColor: adminPalette.card,
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#E9DCCF",
  },
  cardTitle: {
    color: adminPalette.coffee,
    fontSize: 16,
    fontWeight: "700",
  },
  body: {
    color: adminPalette.coffee,
    lineHeight: 22,
    marginTop: 8,
  },
  muted: {
    color: "#8A6B55",
    marginTop: 4,
  },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  statCard: {
    width: "48%",
    backgroundColor: adminPalette.card,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "#E9DCCF",
  },
  statValue: {
    color: adminPalette.coffee,
    fontSize: 28,
    fontWeight: "800",
  },
  rowBetween: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  input: {
    backgroundColor: adminPalette.card,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#D8C1AA",
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: adminPalette.coffee,
    marginTop: 12,
  },
  textArea: {
    minHeight: 94,
    textAlignVertical: "top",
  },
  button: {
    backgroundColor: adminPalette.cocoa,
    borderRadius: 999,
    paddingVertical: 14,
    paddingHorizontal: 18,
    alignItems: "center",
    marginTop: 14,
  },
  buttonText: {
    color: adminPalette.card,
    fontWeight: "800",
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  secondaryButton: {
    borderColor: adminPalette.cocoa,
    borderWidth: 1,
    borderRadius: 999,
    paddingVertical: 14,
    alignItems: "center",
    marginVertical: 16,
  },
  secondaryButtonText: {
    color: adminPalette.coffee,
    fontWeight: "800",
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  badge: {
    color: adminPalette.coffee,
    backgroundColor: adminPalette.linen,
    borderRadius: 999,
    overflow: "hidden",
    paddingHorizontal: 10,
    paddingVertical: 4,
    fontSize: 11,
    fontWeight: "700",
  },
  wrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  chip: {
    borderWidth: 1,
    borderColor: "#D8C1AA",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: adminPalette.card,
  },
  chipActive: {
    backgroundColor: adminPalette.cocoa,
    borderColor: adminPalette.cocoa,
  },
  chipText: {
    color: adminPalette.coffee,
    fontWeight: "700",
  },
  chipActiveText: {
    color: adminPalette.card,
    fontWeight: "700",
  },
  error: {
    color: "#9F1239",
    marginTop: 10,
  },
});
